
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Sep 14 20:03:49 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 42;
  public static final int CHAR = 49;
  public static final int CONST = 9;
  public static final int HASHHASH = 4;
  public static final int LPAREN = 40;
  public static final int SEMI = 36;
  public static final int CONTINUE = 18;
  public static final int LESS = 29;
  public static final int MINUS = 21;
  public static final int RPAREN = 41;
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int BOOL = 50;
  public static final int COMMA = 38;
  public static final int CLASS = 7;
  public static final int INC = 34;
  public static final int DIV = 23;
  public static final int PLUS = 20;
  public static final int IF = 10;
  public static final int DOT = 39;
  public static final int FINDANY = 2;
  public static final int EOF = 0;
  public static final int MOREEQV = 28;
  public static final int RETURN = 15;
  public static final int RBRACKET = 43;
  public static final int EQUAL = 33;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int MUL = 22;
  public static final int NUMBER = 48;
  public static final int MOD = 24;
  public static final int IDENT = 47;
  public static final int BREAK = 6;
  public static final int VOID = 16;
  public static final int EQV = 25;
  public static final int FOREACH = 19;
  public static final int LBRACE = 44;
  public static final int ELSE = 8;
  public static final int IMPLEOF = 46;
  public static final int READ = 14;
  public static final int NOEQV = 26;
  public static final int WHILE = 11;
  public static final int RBRACE = 45;
  public static final int EXTENDS = 17;
  public static final int PROG = 5;
  public static final int LESSEQV = 30;
  public static final int DEC = 35;
  public static final int TWODOTS = 37;
  public static final int PRINT = 13;
  public static final int MORE = 27;
  public static final int FINDANDREPLACE = 3;
}

